# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features
      labels:
        - Semver-Minor
        - enhancement
    - title: Bugfixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
